@baseUrl = http://localhost:8000/api/users
@contentType = application/json
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5MjAyMTM5LCJpYXQiOjE3MzkxOTg1MzksImp0aSI6IjI3YWE1YTkyNTc5ZTRlMDFiNzA5ZDNlZmY0OTUyOTkyIiwidXNlcl9pZCI6Mn0.xiK77zM3c4avuTJmhQBCJOJHDwv-DYB-ORTbFENj3dg

### Register new user

POST {{baseUrl}}/register/
Content-Type: {{contentType}}

{
    "email": "test@example.com",
    "username": "testuser",
    "password": "securepassword123"
}

### Login
POST {{baseUrl}}/login/
Content-Type: {{contentType}}

{
    "email": "test@example.com",
    "password": "securepassword123"
}

### Get user profile (requires authentication)
GET {{baseUrl}}/profile/
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

### Update user profile (requires authentication)
PUT {{baseUrl}}/profile/
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
    "bio": "Updated bio information LOL",
    "username": "updated_username"
}

### Refresh token
POST {{baseUrl}}/token/refresh/
Content-Type: {{contentType}}

{
    "refresh": "your_refresh_token_here"
}
